# Generated by Django 3.2.25 on 2024-07-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240704_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='text',
            field=models.CharField(max_length=50000),
        ),
    ]
