# Generated by Django 3.2.25 on 2024-07-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240704_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speech',
            name='created_at',
        ),
    ]
