# Generated by Django 3.2.25 on 2024-07-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_speech_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutPut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_word', models.CharField(max_length=200)),
                ('mostFrequentWord', models.CharField(max_length=200)),
            ],
        ),
    ]
