# Generated by Django 3.2.25 on 2024-07-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_output'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutPut',
        ),
        migrations.AddField(
            model_name='speech',
            name='mostFrequentWord',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='speech',
            name='unique_phrase',
            field=models.CharField(default='', max_length=200),
        ),
    ]
